### ISSUE TITLE
Argon2 password with php

### ISSUE THREAD

**Issue by nimasdj** [ircmaxell/PHP-PasswordLib#21]
@ircmaxell 
Hi,

Would consider to provide a php code to generate Argon2i and Argon2d password?
Right now, it seems only C version is available and not php.

**Comment by ircmaxell** [comment]
not in pure PHP, but perhaps as an extension.

With pure PHP it would simply be too slow and hence sacrifice a significant margin of security (giving an attacker more advantage)

**Comment by nimasdj** [comment]
Hi,

Is Argon2 stronger than password_hash? If yes, is PHP considering to make Argon2 as a function or extension?

**Comment by ircmaxell** [comment]
Argon2 is stronger than bcrypt. And yes, it is being worked on for 7.1, and would be the default algorithm for the release after that (7.2 or 8).

**Comment by indolering** [comment]
@ircmaxell I'm interested in getting server relief working.  Where's the best place to discuss the implementation side?
